#%- if not included %#
[tool.poetry]
name = "skeleton"
version = "0.1.0"
description = "A copier template for bswck projects."
authors = ["bswck <bartoszpiotrslawecki@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.5,<3.11"
poethepoet = "^0.25.1"
copier = "^9.2.0"
copier-template-tester = "^2.1.1"
copier-templates-extensions = "^0.3.0"

#%- endif %#
[tool.poetry.group.dev-skeleton.dependencies]
# {{_origin|skeleton_notice(snref=snref, srev=srev, scope="dependency group")|indent("# ")}}
mypy = ">=1.9.0"
ruff = ">=0.3.4"
towncrier = ">=23.11.0"
#%- if tests %#
coverage = ">=7.4.4"
pytest = ">=8.1.1"
pytest-doctestplus = ">=1.2.1"
pytest-sugar = ">=1.0.0"
covdefaults = ">=2.3.0"
#%- endif %#
poethepoet = ">=0.25.0"
#%- if precommit %#
pre-commit = "<3.6.0"
#%- endif %#
#%- if public and tests %#
smokeshow = ">=0.4.0"
#%- endif %#
keyring = ">=25.0.0"

#%- if tests %#

[tool.pytest.ini_options]
addopts = "--doctest-modules"
#%- endif %#

#%- if docs %#

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
markdown-exec = ">=1.3.0"
mkdocs-material = ">=8.2,<10.0.0"
mkdocstrings = { version = ">=0.19.0" }
mkdocstrings-python = { git = "git@github.com:pawamoy-insiders/mkdocstrings-python.git" }

#%- endif %#

#%- if not included %#
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
#%- endif %#
